name: outer
version: '0.1.0.0'
category: Acme
author: Rob Berry
maintainer: example@example.com
copyright: ! 'Copyright: (c) 2016 Rob Berry'
license: BSD3
github: rob-b/outer
tested-with: GHC==7.10.2
extra-source-files:
- README.md
library:
  source-dirs: src
  ghc-options: -Wall
  exposed-modules:
  - Outer
  - Outer.Client
  dependencies:
  - base >=4.7 && <5
  - process
  - errors
  - network
  - stm
  - stm-chans
  - transformers
  - resource-pool
  - retry
  - socket
  - bytestring
  - monad-control
  - optparse-applicative
executables:
  outer:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - outer
  couter:
    main: Main.hs
    source-dirs: client
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - outer
tests:
  spec:
    main: Spec.hs
    source-dirs: test
    ghc-options: -Wall
    dependencies:
    - base
    - outer
    - hspec
    - QuickCheck
